__METADATA__
{
  "v3Meta": {
    "objectGuid": "65f97829-ea0b-45a7-b0b0-7a2cb588d021",
    "objectTypeGuid": "6f9dac99-8de1-4efc-8465-68ac443b7d08",
    "embeddedObjectTypeGuids": [
      "a9ed5b7e-75c5-4651-af16-d2c27e98cb94",
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__DECLARATION__
PROGRAM SR_Main
VAR
	xBool1 : BOOL;
END_VAR
__IMPLEMENTATION__

xBool1 := GVL.iVal1 > 2500;

 	
